import 'package:flutter/material.dart';
import 'package:dio/dio.dart';
import './day_article_data.dart';

class DayArticle extends StatefulWidget {
  @override
  _DayArticleState createState() => new _DayArticleState();
}

class _DayArticleState extends State<DayArticle> {
  Data mydata;
  RegExp reg = new RegExp(r"[<p></p>]");

  void _getData() async {
    Dio dio = new Dio();
    Response response =
        await dio.get('https://interface.meiriyiwen.com/article/random?dev=1');
    Autogenerated autogenerated = Autogenerated.fromJson(response.data);

    if (!mounted) {
      return;
    }
    setState(() {
      mydata = autogenerated.data;
      print(mydata);
    });
  }

  @override
  Widget build(BuildContext context) {
    return new Container(
      padding: EdgeInsets.all(20.0),
      child: new ListView(
        children: <Widget>[
          new Container(
            child: new FloatingActionButton(
              backgroundColor: Colors.lightGreen,
              child: new Text('一文'),
              onPressed: _getData,
              
            ),
            alignment: Alignment.bottomRight,
          ),
          mydata != null
              ? new Container(
                  padding: EdgeInsets.only(bottom: 10.0),
                  alignment: Alignment.center,
                  child: new Text(mydata.title,
                      style: new TextStyle(
                          fontSize: 20.0,
                          color: Colors.black,
                          fontWeight: FontWeight.bold)))
              : new Text(''),
          mydata != null
              ? new Container(
                  alignment: Alignment.center,
                  padding: EdgeInsets.only(bottom: 10.0),
                  child: new Text(mydata.author,
                      style: new TextStyle(
                          fontSize: 16.0,
                          color: Colors.grey[800],
                          fontWeight: FontWeight.bold)))
              : new Text(''),
          mydata != null
              ? new Container(
                  alignment: Alignment.center,
                  child: new Text(mydata.content.replaceAll(reg, ''),
                      style: new TextStyle(fontSize: 14.0)))
              : new Text(''),
          // new Text(data.author),
          // new Text(data.content.replaceAll(reg, '')),
        ],
      ),
    );
  }
}
