import 'package:flutter/material.dart';
import 'package:dio/dio.dart';

import './img_data.dart';
import './img_detail_page.dart';

class ImgSimple extends StatefulWidget {
  @override
  _ImgSimpleState createState() => new _ImgSimpleState();
}

class _ImgSimpleState extends State<ImgSimple> {
  List<Data> imgLists = [];

  void _getData() async {
    Dio dio = new Dio();
    Response response = await dio.get('http://wallpaper.apc.360.cn/index.php?c=WallPaperAndroid&a=getAllCategories');
    Autogenerated autogenerated = Autogenerated.fromJson(response.data);

    if (!mounted) {
      return;
    }
    setState(() {
      imgLists = autogenerated.data;
    });
  }

  @override
  Widget build(BuildContext context) {

    _getData();

    return new Container(
      child: ListView(
        children: imgLists.length <=0 ? <Widget>[new Text('暂无数据')]
        : imgLists.map((item){
          return new ListTile(
            leading:new CircleAvatar(
              child:new Icon(Icons.library_music,color: Colors.lightGreen,),
              radius: 20.0,
              backgroundColor: Colors.lightBlue[50],
            ),
            title: Text(item.name),
            subtitle:  Text("${item.totalcnt}"),
            onTap: ()=>{
              _getImgDetailList(item)
            },
          );
        }).toList(),
      ),
    );
  }

  _getImgDetailList(item){
    Navigator.of(context).push(
      new MaterialPageRoute(
        builder: (context){
          return new Scaffold(
            appBar: new AppBar(
              title: new Text(item.name),
            ),
            body: new ImgDetailSimple(id:item.id)
          );
        }
      )
    );
  }
}
