import 'package:flutter/material.dart';
import 'package:dio/dio.dart';
import 'package:transparent_image/transparent_image.dart';
import 'package:flutter/cupertino.dart';
import './img_detail_data.dart';

class ImgDetailSimple extends StatefulWidget {
  ImgDetailSimple({Key key, this.id}) : super(key: key);
  final String id;

  @override
  _ImgDetailSimpleState createState() => new _ImgDetailSimpleState();
}

class _ImgDetailSimpleState extends State<ImgDetailSimple> {
  List<Data> imgLists = [];
  bool loading = false;

  void _getData() async {
    setState(() {
      loading = true;
    });
    Dio dio = new Dio();
    Response response = await dio.get(
        'http://wallpaper.apc.360.cn/index.php?c=WallPaperAndroid&a=getAppsByCategory&cid=${widget.id}&start=0&count=99');
    Autogenerated autogenerated = Autogenerated.fromJson(response.data);

    if (!mounted) {
      return;
    }
    setState(() {
      imgLists = autogenerated.data;
      loading = false;
    });
  }

  _init() {
    if (imgLists.length <= 0) {
      _getData();
    }
  }

  @override
  Widget build(BuildContext context) {
    _init();

    return new Center(
      child: loading
          ? new Container(
              child: new CupertinoActivityIndicator(radius: 20.0),
              color: Colors.grey[400],
              width: double.infinity,
              height: double.infinity,
            )
          : ListView(
              children: imgLists.length <= 0
                  ? <Widget>[new Text('暂无数据')]
                  : imgLists.map((item) {
                      return new Container(
                          padding: EdgeInsets.all(10.0),
                          child: new FadeInImage.memoryNetwork(
                              placeholder: kTransparentImage, image: item.url)
                          // new Image.network(item.url),
                          );
                    }).toList()),
    );
  }
}
