import 'package:flutter/material.dart';
import 'package:dio/dio.dart';
import './img_data.dart';

class ImgSimple extends StatefulWidget {
  @override
  _ImgSimpleState createState() => new _ImgSimpleState();
}

class _ImgSimpleState extends State<ImgSimple> {
  List<Data> imgList = [];

  void _getData() async {
    Dio dio = new Dio();
    Response response = await dio.get('https://www.apiopen.top/meituApi?page=1');
    AutogeneratedImg autogeneratedImg = AutogeneratedImg.fromJson(response.data);

    if (!mounted) {
      return;
    }
    setState(() {
      imgList = autogeneratedImg.data;
    });
  }

  @override
  Widget build(BuildContext context) {
    _getData();

    return new Container(
      padding: EdgeInsets.only(top: 10, bottom: 10),
      child: new ListView(
        children: imgList.length <= 0
            ? <Widget>[new Text('暂无数据')]
            : imgList.map(
                (item) {
                  
                  return new Container(
                    child: new Image.network(item.url.replaceAll('http', 'https')),
                    width: 300.0,
                    height: 200.0
                  );
                },
              ).toList(),
      ),
    );
  }
}
