class AutogeneratedImg {
  int code;
  String msg;
  List<Data> data;

  AutogeneratedImg({this.code, this.msg, this.data});

  AutogeneratedImg.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    msg = json['msg'];
    if (json['data'] != null) {
      data = new List<Data>();
      json['data'].forEach((v) {
        data.add(new Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['code'] = this.code;
    data['msg'] = this.msg;
    if (this.data != null) {
      data['data'] = this.data.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Data {
  String createdAt;
  String publishedAt;
  String type;
  String url;

  Data({this.createdAt, this.publishedAt, this.type, this.url});

  Data.fromJson(Map<String, dynamic> json) {
    createdAt = json['createdAt'];
    publishedAt = json['publishedAt'];
    type = json['type'];
    url = json['url'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['createdAt'] = this.createdAt;
    data['publishedAt'] = this.publishedAt;
    data['type'] = this.type;
    data['url'] = this.url;
    return data;
  }
}