import 'package:flutter/material.dart';
import 'package:dio/dio.dart';
import './poetry_data.dart';

class PoetrySimple extends StatefulWidget {
  @override
  _PoetrySimpleState createState() => new _PoetrySimpleState();
}

class _PoetrySimpleState extends State<PoetrySimple> {
  List<Result> poetryList = [];

  @override
  Widget build(BuildContext context) {
    void _getData() async {
      Dio dio = new Dio();
      Response response = await dio
          .get("https://api.apiopen.top/getSongPoetry?page=1&count=100");
      AutogeneratedPoetry autogeneratedPoetry =
          AutogeneratedPoetry.fromJson(response.data);

      if(!mounted){
        return;
      }
      setState(() {
        poetryList = autogeneratedPoetry.result;
      });
    }

    _getData();
    return  new Container(
          padding: EdgeInsets.only(top: 10, bottom: 10),
          child: new ListView(
            children: poetryList.length <= 0
                ?<Widget>[new Text('暂无数据')] 
                : poetryList.map(
                    (item) {
                      return new Container(
                        child: ListTile(
                          leading: new CircleAvatar(
                            child: new Text(item.authors,
                                style: new TextStyle(fontSize: 10.0)),
                          ),
                          title: new Text(item.title),
                          subtitle: new Text(item.content),
                        ),
                      );
                    },
                  ).toList(),
          ),
    );
  }
}
