class AutogeneratedPoetry {
  int code;
  String message;
  List<Result> result;

  AutogeneratedPoetry({this.code, this.message, this.result});
  AutogeneratedPoetry.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    message = json['message'];

    if (json['result'] != null) {
      result = new List<Result>();

      json['result'].forEach((v) {
        result.add(new Result.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();

    data['code'] = this.code;
    data['message'] = this.message;

    if (this.result != null) {
      data['result'] = this.result.map((v) => v.toJson()).toList();
    }

    return data;
  }
}

class Result {
  String title;
  String content;
  String authors;

  Result({this.title, this.content, this.authors});
  Result.fromJson(Map<String, dynamic> json) {
    title = json['title'];
    content = json['content'];
    authors = json['authors'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['title'] = this.title;
    data['content'] = this.content;
    data['authors'] = this.authors;
    return data;
  }
}