import 'package:flutter/material.dart';
import 'package:dio/dio.dart';
import './musicList_data.dart';
import './video_page.dart';


class MusicListSimple extends StatefulWidget {

  MusicListSimple({Key key,this.id}):super(key:key);
  final int id;

  @override
  _MusicListSimpleState createState() => new _MusicListSimpleState();
}
 
class _MusicListSimpleState extends State<MusicListSimple> {

 List<SongList> musicLists = [];

    void getData() async {
    Dio dio = new Dio();
    Response response = await dio.get("https://music.niubishanshan.top/api/v2/music/songList/${widget.id}");
    Autogenerated autogenerated = Autogenerated.fromJson(response.data);

    if (!mounted) {
      return;
    }
    setState(() {
      musicLists = autogenerated.data.songList;
    });
  }
  @override
  Widget build(BuildContext context) {
    getData();
    return new Container(
      child: ListView(
        children: musicLists.map((item){
           return new ListTile(
             leading:new CircleAvatar(child: new Text(item.singer[0].singerName,style:new TextStyle(fontSize:10.0),),),
             title: new Text(item.songName),
             onTap: (){
               _goMusicdetail(item);
             },
           );
        }).toList(),
      ),
    );
  }

    void _goMusicdetail(item){
      Navigator.of(context).push(
        new MaterialPageRoute(
          builder: (context){
            return new Scaffold(
              appBar: new AppBar(
                title: new Text(item.songName),
              ),
              body:
              new VideoSimple(id:item.songMid)
            );
          }
        ),
      );
  }
}