class Autogenerated {
  String announce;
  int errno;
  String msg;
  Data data;

  Autogenerated({this.announce, this.errno, this.msg, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    announce = json['announce'];
    errno = json['errno'];
    msg = json['msg'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['announce'] = this.announce;
    data['errno'] = this.errno;
    data['msg'] = this.msg;
    if (this.data != null) {
      data['data'] = this.data.toJson();
    }
    return data;
  }
}

class Data {
  String updateTime;
  int totalSongNum;
  TopInfo topInfo;
  List<SongList> songList;

  Data({this.updateTime, this.totalSongNum, this.topInfo, this.songList});

  Data.fromJson(Map<String, dynamic> json) {
    updateTime = json['updateTime'];
    totalSongNum = json['totalSongNum'];
    topInfo =
        json['topInfo'] != null ? new TopInfo.fromJson(json['topInfo']) : null;
    if (json['songList'] != null) {
      songList = new List<SongList>();
      json['songList'].forEach((v) {
        songList.add(new SongList.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['updateTime'] = this.updateTime;
    data['totalSongNum'] = this.totalSongNum;
    if (this.topInfo != null) {
      data['topInfo'] = this.topInfo.toJson();
    }
    if (this.songList != null) {
      data['songList'] = this.songList.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class TopInfo {
  String picAlbum;
  String listName;

  TopInfo({this.picAlbum, this.listName});

  TopInfo.fromJson(Map<String, dynamic> json) {
    picAlbum = json['picAlbum'];
    listName = json['listName'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['picAlbum'] = this.picAlbum;
    data['listName'] = this.listName;
    return data;
  }
}

class SongList {
  String songMid;
  List<Singer> singer;
  String songName;
  int songId;
  String albumMid;

  SongList(
      {this.songMid, this.singer, this.songName, this.songId, this.albumMid});

  SongList.fromJson(Map<String, dynamic> json) {
    songMid = json['songMid'];
    if (json['singer'] != null) {
      singer = new List<Singer>();
      json['singer'].forEach((v) {
        singer.add(new Singer.fromJson(v));
      });
    }
    songName = json['songName'];
    songId = json['songId'];
    albumMid = json['albumMid'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['songMid'] = this.songMid;
    if (this.singer != null) {
      data['singer'] = this.singer.map((v) => v.toJson()).toList();
    }
    data['songName'] = this.songName;
    data['songId'] = this.songId;
    data['albumMid'] = this.albumMid;
    return data;
  }
}

class Singer {
  String singerName;
  String singerMid;

  Singer({this.singerName, this.singerMid});

  Singer.fromJson(Map<String, dynamic> json) {
    singerName = json['singerName'];
    singerMid = json['singerMid'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['singerName'] = this.singerName;
    data['singerMid'] = this.singerMid;
    return data;
  }
}