class Autogenerated {
  String announce;
  int errno;
  String msg;
  List<Data> data;

  Autogenerated({this.announce, this.errno, this.msg, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    announce = json['announce'];
    errno = json['errno'];
    msg = json['msg'];
    if (json['data'] != null) {
      data = new List<Data>();
      json['data'].forEach((v) {
        data.add(new Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['announce'] = this.announce;
    data['errno'] = this.errno;
    data['msg'] = this.msg;
    if (this.data != null) {
      data['data'] = this.data.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Data {
  int id;
  String title;
  int listenCount;
  String picUrl;
  List<SongList> songList;

  Data({this.id, this.title, this.listenCount, this.picUrl, this.songList});

  Data.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    listenCount = json['listenCount'];
    picUrl = json['picUrl'];
    if (json['songList'] != null) {
      songList = new List<SongList>();
      json['songList'].forEach((v) {
        songList.add(new SongList.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    data['listenCount'] = this.listenCount;
    data['picUrl'] = this.picUrl;
    if (this.songList != null) {
      data['songList'] = this.songList.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class SongList {
  String singerName;
  String songName;
  int number;

  SongList({this.singerName, this.songName, this.number});

  SongList.fromJson(Map<String, dynamic> json) {
    singerName = json['singerName'];
    songName = json['songName'];
    number = json['number'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['singerName'] = this.singerName;
    data['songName'] = this.songName;
    data['number'] = this.number;
    return data;
  }
}