import 'package:flutter/material.dart';
import 'package:dio/dio.dart';
import './topList_data.dart';
import './musicList_page.dart';

class TopListSimple extends StatefulWidget {
  @override
  _TopListSimpleState createState() => new _TopListSimpleState();
}

class _TopListSimpleState extends State<TopListSimple> {
  List<Data> musicLists = [];

  void getData() async {
    Dio dio = new Dio();
    Response response =
        await dio.get("https://music.niubishanshan.top/api/v2/music/toplist");
    Autogenerated autogenerated = Autogenerated.fromJson(response.data);

    if (!mounted) {
      return;
    }
    setState(() {
      musicLists = autogenerated.data;
    });
  }

  @override
  Widget build(BuildContext context) {
    getData();
    return new Container(
          height: 500.0,
          width: 500.0,
          padding: EdgeInsets.only(top: 10, bottom: 10),
          child: new ListView(
            children: musicLists.length <= 0
                ? <Widget>[new Text('暂无数据')]
                : musicLists.map((item) {
                    return new Container(
                      child: new ListTile(
                        leading: new CircleAvatar(
                          child: new Image.network(item.picUrl),
                        ),
                        title: new Text(item.title),
                        subtitle: new Text('收听次数：${item.listenCount}'),
                        onTap: (){
                          _goMusicList(item);
                        },
                      ),
                    );
                  }).toList(),
          ),
    );
  }


  void _goMusicList(item){
      Navigator.of(context).push(
        new MaterialPageRoute(
          builder: (context){
            return new Scaffold(
              appBar: new AppBar(
                title: new Text(item.title+'音乐列表'),
              ),
              body: new MusicListSimple(id:item.id)
            );
          }
        ),
      );
  }
}
