class Autogenerated {
  String announce;
  int errno;
  String msg;
  List<String> data;

  Autogenerated({this.announce, this.errno, this.msg, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    announce = json['announce'];
    errno = json['errno'];
    msg = json['msg'];
    data = json['data'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['announce'] = this.announce;
    data['errno'] = this.errno;
    data['msg'] = this.msg;
    data['data'] = this.data;
    return data;
  }
}